#!/bin/bash
# QA Agent Manual Verification Runner
# Generates timestamped output files for each verification run

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FINDINGS_DIR="$SCRIPT_DIR/findings"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_FILE="$FINDINGS_DIR/${TIMESTAMP}_qa_verification.md"

cd "$REPO_ROOT"

echo "# QA Agent Verification Findings" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "**Timestamp**: $(date '+%Y-%m-%d %H:%M:%S')" >> "$OUTPUT_FILE"
echo "**Verification Run ID**: $TIMESTAMP" >> "$OUTPUT_FILE"
echo "**Environment**: Python $(python3 --version 2>&1 | cut -d' ' -f2), pytest $(python3 -c 'import pytest; print(pytest.__version__)')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Automated Test Results" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Run import verification
echo "### Import Verification" >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
python3 -c "
from swarm_attack.qa.agents import ContractValidatorAgent, EndpointDiscoveryError
from swarm_attack.qa.models import QATrigger, AuthStrategy
print('QATrigger:', [t.value for t in QATrigger])
print('AuthStrategy:', [s.value for s in AuthStrategy])
print('ContractValidatorAgent: OK')
" 2>&1 >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Run edge case tests
echo "### Edge Case Tests" >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
PYTHONPATH=. python3 -m pytest \
    tests/unit/qa/test_auth_edge_cases.py \
    tests/unit/qa/test_response_validation_edge_cases.py \
    tests/unit/qa/test_request_generation_edge_cases.py \
    tests/unit/qa/test_database_state_edge_cases.py \
    -v --tb=short 2>&1 | tail -30 >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Run full QA suite
echo "### Full QA Suite Summary" >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
PYTHONPATH=. python3 -m pytest tests/unit/qa/ -v --tb=short 2>&1 | tail -10 >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Manual Review Required" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Use the prompt at \`tests/manual/QA_AGENT_VERIFICATION_PROMPT.md\` to:" >> "$OUTPUT_FILE"
echo "1. Analyze any failures above" >> "$OUTPUT_FILE"
echo "2. Root cause issues with expert panel" >> "$OUTPUT_FILE"
echo "3. Plan fixes" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Generated by run_verification.sh*" >> "$OUTPUT_FILE"

echo ""
echo "Verification complete! Output written to:"
echo "  $OUTPUT_FILE"
echo ""
echo "To review with Claude, run:"
echo "  cat $OUTPUT_FILE | claude"
